# https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

name: 'YAML to RSS'
description: 'YAML to RSS'
runs:
  using: 'docker'
  image: 'ghcr.io/opensource-f2f/open-podcasts-yaml-rss:dev'
