name: Release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.16.x
      - name: Build
        run: |
          sudo apt-get update -y
          sudo apt install libasound2-dev -y
          GOENABLE=0 go build -o bin/goplay .
          cd bin && tar czvf goplay-linux-amd64.tar.gz goplay
          pwd
          gh release upload ${{ github.ref_name }} bin/goplay-linux-amd64.tar.gz

  build-darwin:
    name: BuildOnDarwin
    runs-on: macos-10.15
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.5
      - name: Build
        run: |
          GOENABLE=0 go build -o bin/goplay .
          cd bin && tar czvf goplay-darwin-amd64.tar.gz goplay
          pwd
          gh release upload ${{ github.ref_name }} bin/goplay-darwin-amd64.tar.gz
