name: Release

on:
  push:
    tags:
      - '*'

jobs:
  BuildOnLinux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.16.x
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUBLISH_SECRETS }}
        run: |
          sudo apt-get update -y
          sudo apt install libasound2-dev -y
          GOENABLE=0 go build -ldflags '-X github.com/linuxsuren/cobra-extension/version.version=${{ github.ref_name }} -X github.com/linuxsuren/cobra-extension/version.commit=${{ github.sha }}' -o bin/goplay .
          cd bin && tar czvf goplay-linux-amd64.tar.gz goplay
          gh release upload ${{ github.ref_name }} goplay-linux-amd64.tar.gz
  BuildOnDarwin:
    runs-on: macos-10.15
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.5
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUBLISH_SECRETS }}
        run: |
          GOENABLE=0 go build -ldflags '-X github.com/linuxsuren/cobra-extension/version.version=${{ github.ref_name }} -X github.com/linuxsuren/cobra-extension/version.commit=${{ github.sha }}' -o bin/goplay .
          cd bin && tar czvf goplay-darwin-amd64.tar.gz goplay
          gh release upload ${{ github.ref_name }} goplay-darwin-amd64.tar.gz
