name: Release Drafter

on:
  push:
    branches:
      - lab-osf2f

jobs:
  UpdateReleaseDraft:
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUBLISH_SECRETS }}
  PublishLab:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.5
      - name: Login
        run: |
          docker login ghcr.io/linuxsuren -u linuxsuren -p${{secrets.GH_PUBLISH_SECRETS}}
      - name: Publish Backend Image
        run: |
          docker build lab/osf2f -t ghcr.io/linuxsuren/goplay:osf2f-dev
          docker push ghcr.io/linuxsuren/goplay:osf2f-dev
      - name: Publish UI Image
        run: |
          docker build lab/ui -t ghcr.io/linuxsuren/goplay:osf2f-ui-dev
          docker push ghcr.io/linuxsuren/goplay:osf2f-ui-dev
