name: Release

on:
  push:
    tags:
      - '*'

jobs:
  BuildController:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.16.x
      - name: Login
        run: |
          docker login ghcr.io/opensource-f2f -u linuxsuren -p${{secrets.GH_PUBLISH_SECRETS}}
      - name: Publish Backend Image
        run: |
          IMG=ghcr.io/opensource-f2f/open-podcasts:${{ github.ref_name }} make docker-build docker-push

  BuildAPIServer:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.16.x
      - name: Login
        run: |
          docker login ghcr.io/opensource-f2f -u linuxsuren -p${{secrets.GH_PUBLISH_SECRETS}}
      - name: Publish APIServer Image
        run: |
          IMG-UI=ghcr.io/opensource-f2f/open-podcasts-apiserver:${{ github.ref_name }} make docker-build-apiserver docker-push-apiserver

  BuildUI:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.16.x
      - name: Login
        run: |
          docker login ghcr.io/opensource-f2f -u linuxsuren -p${{secrets.GH_PUBLISH_SECRETS}}
      - name: Publish UI Image
        run: |
          IMG-UI=ghcr.io/opensource-f2f/open-podcasts-ui:${{ github.ref_name }} make docker-build-ui docker-push-ui
